name: Public AUR gnome-shell-extension-screen-autorotate

on:
  push:
    paths:
      - "pkgbuild/gnome-shell-extension-screen-autorotate/PKGBUILD"
  workflow_dispatch:

jobs:
  public_aur:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Update PKGBUILD
      #   id: update
      #   run: |
      #     git clone https://github.com/pelrun/pyWinControls.git && cd pyWinControls
      #     git fetch --unshallow
      #     pkgver=$(git describe --tags --abbrev=0 | sed 's/^v//')
      #     echo "Updating PKGBUILD to version $pkgver"
      #     cd ..
      #     sed -i "s/^pkgver=.*/pkgver=$pkgver/" PKGBUILD
      #     cat PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: gnome-shell-extension-screen-autorotate
          pkgbuild: pkgbuild/gnome-shell-extension-screen-autorotate/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
