name: Public AUR pyWinControls

on:
  push:
    paths:
      - "pkgbuild/gpdconfig-git/PKGBUILD"
  workflow_dispatch:

jobs:
  public_aur:
    runs-on: ubuntu-latest
    if: ! startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update PKGBUILD
        id: update
        run: |
          git clone https://github.com/pelrun/pyWinControls.git && cd pyWinControls
          git fetch
          pkgver=$(printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)")
          cd ..
          tree
          echo "Updating PKGBUILD to version $pkgver"
          sed -i "s/^pkgver=.*/pkgver=$pkgver/" pkgbuild/gpdconfig-git/PKGBUILD

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: gpdconfig-git
          pkgbuild: pkgbuild/gpdconfig-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
